language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - "py.test tests.py"

notifications:
  webhooks:
    urls:
      - http://learn.rmotr.com/webhooks/travis/build-finished
    on_success: always
    on_failure: always
    on_start: never
